name: Git Commit & Push
description: Configures git and commits staged files

inputs:
  message:
    description: Commit message
    required: true

runs:
  using: composite
  steps:
    - name: Commit and push
      shell: bash
      run: |
        git config --global user.name "$BOT_NAME"
        git config --global user.email "$BOT_EMAIL"
        git add -A
        git commit -m "${{ inputs.message }}" || exit 0
        git push
