name: Generate Readme

on: 
  push:
    branches: ["main"]
    paths: 
      - "main.py"
      - "README.md.rst"
  pull_request:
    branches: ["main"]
    paths: 
      - "main.py"
      - "README.md.rst"
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Generate
        run: python main.py

      - name: Commit Generate
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          git add README.md
          git commit -m 'chore: updated generated readme'
          git push
